[package]
name = "notsu"
version = "0.1.0"
description = "An unofficial community desktop companion"
edition = "2021"
rust-version = "1.88"

[lib]
name = "notsu_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
